### ISSUE TITLE
EPIC 1 : CRETION OF THE PROJECT AND BASIC ENVIROMENT SET UP

### ISSUE THREAD

**Issue by hugoht3** [hugoht3/cine-vault#1]
Epic Description : Set up the project repository and manage the Heroku deployment.

- [x] Task 1 : Create the project repository on Gitpod.
- [x] Task 2 : Create a basic working Django web app.
- [x] Task 3 : Deploy project to heroku.
