### ISSUE TITLE
EPIC 2 : CREATION OF DATABASE AND MODELS

### ISSUE THREAD

**Issue by hugoht3** [hugoht3/cine-vault#2]
Epic Description : configure database, manage environment variables, create models.

 - [x] Task 1 : Create cloud-based database and wire it to the project.
 - [x] Task 2 :  Determine the database schema and create the models required for project.
 - [x] Task 3 :  Make migrations for all models.
