### ISSUE TITLE
EPIC 3 : ADMINISTRATION PANEL

### ISSUE THREAD

**Issue by hugoht3** [hugoht3/cine-vault#3]
Epic Description : Site admins competence & tasks.

Acceptance Criteria as admin:
Creation of the basics of CRUD (create, read, update and delete) functionality 
Creation of  draft posts Give movies ratings.
Approval or disapproval of comments
Review and acceptance of movie recommendation forms (logged users)

- [x] Tasks 1 : Create the admin panel.
- [x] Tasks 2 : CRUD
- [x] Tasks 3 : creating drafts
- [ ] Tasks 4 : ratings
- [x] Tasks 5 : comment approval
- [ ] Tasks 6 : review movie recommandations
- [ ] Tasks 7 : test out the all functions as admin
