### ISSUE TITLE
EPIC 4 : VALIDATION AND TESTS

### ISSUE THREAD

**Issue by hugoht3** [hugoht3/cine-vault#4]
Epic Description : All testing and validation required for the project.

- [ ]  Task 1 : Do manual testing.
- [ ]  Task 2 : W3C HTML validation.
- [ ]  Task 3 : W3C CSS validation.
- [ ]  Task 4 : PEP8 validation.
- [ ]  Task 5 : JS Lint.
